version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.4
    working_directory: /go/src/github.com/PagerDuty/go-pagerduty
    steps:
      - checkout
      - run:
          name: "Build"
          command: make build
